#!/bin/bash
# Quick Start Guide for Route Optimization Feature

echo "=================================="
echo "Route Optimization Feature"
echo "Quick Start Guide"
echo "=================================="
echo ""

echo "📋 FILES TO REVIEW:"
echo "1. ROUTE_OPTIMIZATION_IMPLEMENTATION.md - Complete technical documentation"
echo "2. ROUTE_OPTIMIZATION_SUMMARY.md - Feature summary and overview"
echo "3. test-route-optimization-v2.js - Test script with valid token"
echo ""

echo "🔧 IMPLEMENTATION FILES:"
echo "1. src/modules/itineraries/itineraries.controller.ts"
echo "   - Added @ApiQuery for 'type' parameter"
echo "   - Modified createPlan() signature"
echo ""
echo "2. src/modules/itineraries/itineraries.service.ts"
echo "   - Updated createPlan() to accept shouldOptimizeRoute parameter"
echo "   - Added 6 new optimization methods:"
echo "     • optimizeRouteOrder()"
echo "     • calculateDistanceMatrix()"
echo "     • findOptimalRouteTSP()"
echo "     • nearestNeighborWithSimulatedAnnealing()"
echo "     • nearestNeighbor()"
echo "     • calculateTotalDistance()"
echo ""

echo "🧪 HOW TO TEST:"
echo ""
echo "Step 1: Start NestJS server"
echo "  cd d:\\wamp64\\www\\dvi_fullstack\\dvi_backend"
echo "  npm run start:dev"
echo ""
echo "Step 2: Run test script (in another terminal)"
echo "  node tmp/test-route-optimization-v2.js"
echo ""

echo "✅ EXPECTED BEHAVIOR:"
echo "- Server receives POST request with ?type=itineary_basic_info_with_optimized_route"
echo "- Routes are analyzed and reordered to minimize distance"
echo "- Dates are automatically recalculated for new order"
echo "- Response includes optimized route sequence"
echo ""

echo "🎯 KEY FEATURES:"
echo "✓ Exhaustive search for ≤10 routes (guaranteed optimal)"
echo "✓ Nearest Neighbor + Simulated Annealing for >10 routes"
echo "✓ Automatic date recalculation"
echo "✓ First and last routes locked (arrival/departure)"
echo "✓ Comprehensive logging"
echo "✓ Type-safe TypeScript implementation"
echo ""

echo "📊 ALGORITHM SELECTION:"
echo "Number of Routes | Algorithm"
echo "≤10             | Exhaustive TSP (O(n!))"
echo ">10             | Nearest Neighbor + SA (O(n²))"
echo ""

echo "🔗 ENDPOINT:"
echo "POST /api/v1/itineraries?type=itineary_basic_info_with_optimized_route"
echo ""

echo "💼 INTEGRATION WITH FRONTEND:"
echo "When user clicks 'Optimize Route' button in UI:"
echo ""
echo "  fetch('/api/v1/itineraries?type=itineary_basic_info_with_optimized_route', {"
echo "    method: 'POST',"
echo "    headers: {"
echo "      'Authorization': \`Bearer \${token}\`,"
echo "      'Content-Type': 'application/json'"
echo "    },"
echo "    body: JSON.stringify(itineraryData)"
echo "  })"
echo ""

echo "🚀 STATUS: READY FOR TESTING & INTEGRATION"
echo ""
