-- CreateTable `tbo_hotel_booking_confirmation`
CREATE TABLE `tbo_hotel_booking_confirmation` (
  `tbo_hotel_booking_confirmation_ID` INT NOT NULL AUTO_INCREMENT,
  `confirmed_itinerary_plan_ID` INT NOT NULL DEFAULT 0,
  `itinerary_plan_ID` INT NOT NULL DEFAULT 0,
  `itinerary_route_ID` INT NOT NULL DEFAULT 0,
  `tbo_hotel_code` VARCHAR(50) NOT NULL,
  `tbo_booking_id` VARCHAR(100),
  `tbo_booking_reference_number` VARCHAR(100),
  `tbo_trace_id` VARCHAR(100),
  `booking_code` LONGTEXT NOT NULL,
  `check_in_date` DATE,
  `check_out_date` DATE,
  `number_of_rooms` INT NOT NULL DEFAULT 0,
  `net_amount` FLOAT NOT NULL DEFAULT 0,
  `guest_nationality` VARCHAR(10),
  `total_guests` INT NOT NULL DEFAULT 0,
  `api_response` JSON,
  `createdby` INT NOT NULL DEFAULT 0,
  `createdon` DATETIME DEFAULT NOW(),
  `updatedon` DATETIME,
  `status` TINYINT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,

  PRIMARY KEY (`tbo_hotel_booking_confirmation_ID`),
  INDEX `idx_tbo_booking_confirmed_plan_id` (`confirmed_itinerary_plan_ID`),
  INDEX `idx_tbo_booking_itinerary_plan_id` (`itinerary_plan_ID`),
  INDEX `idx_tbo_booking_route_id` (`itinerary_route_ID`),
  INDEX `idx_tbo_booking_hotel_code` (`tbo_hotel_code`),
  INDEX `idx_tbo_booking_id` (`tbo_booking_id`),
  INDEX `idx_tbo_booking_ref_number` (`tbo_booking_reference_number`),
  INDEX `idx_tbo_booking_check_in_date` (`check_in_date`),
  INDEX `idx_tbo_booking_check_out_date` (`check_out_date`),
  INDEX `idx_tbo_booking_createdby` (`createdby`),
  INDEX `idx_tbo_booking_createdon` (`createdon`),
  INDEX `idx_tbo_booking_status` (`status`),
  INDEX `idx_tbo_booking_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
